<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/02/28 17:14:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=bitnami_orangehrm',
  'username' => 'bn_orangehrm',
  'password' => '38ae1b7750',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
